export const FETCH_ALL_PRODUCT = 'FETCH_ALL_PRODUCT';
export const GET_ALL_CART = 'GET_ALL_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_ITEM_IN_CART = 'DELETE_ITEM_IN_CART';
export const INCREASE_QUANTITY_CART = 'INCREASE_QUANTITY_CART';
export const DECREASE_QUANTITY_CART = 'DECREASE_QUANTITY_CART';
export const CHECKOUT_PAYMENT = 'CHECKOUT_PAYMENT';
export const EMPTY_CART = 'EMPTY_CART';